# spring:
#   application:
#     name: Config-Default
#these are the common configuration that can be used for registering with eureka client server
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
